{% set version = "1.5.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-datamods
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/datamods_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/datamods/datamods_{{ version }}.tar.gz
  sha256: 12c581fc9dc0a59fd23a2d309e7dba04231926858ff3b23b59fc66392037a1b8

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-classint
    - r-data.table
    - r-htmltools
    - r-phosphoricons
    - r-reactable
    - r-readxl
    - r-rio
    - r-rlang
    - r-shiny >=1.5.0
    - r-shinywidgets >=0.7.3
    - r-shinybusy
    - r-tibble
    - r-toastui >=0.3.3
    - r-writexl
  run:
    - r-base
    - r-classint
    - r-data.table
    - r-htmltools
    - r-phosphoricons
    - r-reactable
    - r-readxl
    - r-rio
    - r-rlang
    - r-shiny >=1.5.0
    - r-shinywidgets >=0.7.3
    - r-shinybusy
    - r-tibble
    - r-toastui >=0.3.3
    - r-writexl

test:
  commands:
    - $R -e "library('datamods')"           # [not win]
    - "\"%R%\" -e \"library('datamods')\""  # [win]

about:
  home: https://github.com/dreamRs/datamods
  license: GPL-3.0-only
  summary: "'Shiny' modules to import data into an application or 'addin' from various sources, and to manipulate them after that."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: datamods
# Title: Modules to Import and Manipulate Data in 'Shiny'
# Version: 1.2.0
# Authors@R: c(person(given = "Victor", family = "Perrier", role = c("aut", "cre", "cph"), email = "victor.perrier@dreamrs.fr"), person(given = "Fanny", family = "Meyer", role = "aut"), person(given = "Zauad Shahreer", family = "Abeer", role = "aut", email = "shahreyar.abeer@gmail.com"))
# Description: 'Shiny' modules to import data into an application or 'addin' from various sources, and to manipulate them after that.
# License: GPL-3
# URL: https://github.com/dreamRs/datamods
# BugReports: https://github.com/dreamRs/datamods/issues
# Encoding: UTF-8
# RoxygenNote: 7.1.2
# Imports: data.table, DT, htmltools, phosphoricons, readxl, rio, rlang, shiny (>= 1.5.0), shinyWidgets (>= 0.5.3), tibble, tools
# Suggests: jsonlite, knitr, MASS, rmarkdown, testthat, validate
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2021-11-23 17:28:02 UTC; perri
# Author: Victor Perrier [aut, cre, cph], Fanny Meyer [aut], Zauad Shahreer Abeer [aut]
# Maintainer: Victor Perrier <victor.perrier@dreamrs.fr>
# Repository: CRAN
# Date/Publication: 2021-11-23 19:30:07 UTC
